In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv
/kaggle/input/datasets/tsukasahamaoka/ensemble-resources/Kfold_submit.csv
/kaggle/input/datasets/tsukasahamaoka/ensemble-resources/randomforest_reenginerring_submit.csv

# アンサンブル
Random Forestと同じように、いろんな手法の結果をまとめる

今後のテストデータの更新など、対応に幅を持たせる意味で重要。

In [2]:
# ファイルの読み込みと名前付け
submit1 = pd.read_csv('/kaggle/input/datasets/tsukasahamaoka/ensemble-resources/Kfold_submit.csv')
submit2 = pd.read_csv('/kaggle/input/datasets/tsukasahamaoka/ensemble-resources/randomforest_reenginerring_submit.csv')

# 各値を確認
submit_all = pd.DataFrame({'submit1': submit1['Survived'].values,
                            'submit2': submit2['Survived'].values,})

submit_all.head()

   submit1  submit2
0        0        0
1        0        1
2        0        0
3        0        0
4        0        1

In [3]:
submit_all.corr()
# なるべく似たような相関を持つつまり似たようなアルゴリズムはアンサンブルしない

          submit1   submit2
submit1  1.000000  0.768868
submit2  0.768868  1.000000

In [4]:
# 加算
submit_ensemble = pd.read_csv('/kaggle/input/titanic/gender_submission.csv')
submit_ensemble['Survived'] = submit1['Survived'] + submit2['Survived']

submit_ensemble.tail()

     PassengerId  Survived
413         1305         0
414         1306         2
415         1307         0
416         1308         0
417         1309         0

In [5]:
# 結果が2以上なら生存とみなす
submit_ensemble['Survived'] = (submit_ensemble['Survived'] >= 2).astype(int)
submit_ensemble.to_csv("ensemble_submit.csv", index = False)